import React from 'react'

const Head = () => {
  return (
    <>
      <title>e2e lesson</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    </>
  )
}

export default Head
